//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Card = new HashSet<Card>();
        }
    
        public int AccountID { get; set; }
        public int ClientID { get; set; }
        public int DepositTypeID { get; set; }
        public string AccountNumber { get; set; }
        public double MoneyAmount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int DaysCount { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> PercentAccountID { get; set; }
        public bool IsClosed { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual DepositType DepositType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
    }
}
