//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankResourse
    {
        public int ResourseID { get; set; }
        public double RealMoney { get; set; }
        public double PhysicalMoney { get; set; }
        public int CurrencyID { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
