//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronimic { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string Authority { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string IdentificationNumber { get; set; }
        public string PlaceOfBirth { get; set; }
        public int Location { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public int MaritalStatus { get; set; }
        public int Nationality { get; set; }
        public int Disability { get; set; }
        public bool Pensioner { get; set; }
        public Nullable<decimal> MonthlyIncome { get; set; }
        public int RegistrationCity { get; set; }
        public bool Gender { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Disability Disability1 { get; set; }
        public virtual MaritualStatus MaritualStatus { get; set; }
        public virtual Nationality Nationality1 { get; set; }
    }
}
